# https://doc.qt.io/qt-6/macos.html
c_stdlib_version:  # [not linux]
  - 12.0           # [osx]
  - 2022.12        # [win]
OSX_SDK_VER:       # [osx]
  - 14.5           # [osx]

# https://doc.qt.io/qt-6/windows.html
c_compiler:    # [win]
  - vs2022     # [win]
cxx_compiler:  # [win]
  - vs2022     # [win]

# XCode 15.0 came with SDK 14.0 and clang 15
# https://en.wikipedia.org/wiki/Xcode
c_compiler_version:    # [osx]
  - 20                 # [osx]
cxx_compiler_version:  # [osx]
  - 20                 # [osx]

CONDA_BUILD_SYSROOT:
  - /Library/Developer/CommandLineTools/SDKs/MacOSX14.5.sdk  # [osx]
