# https://doc.qt.io/qt-6/macos.html
c_stdlib_version:  # [not linux]
  - 12.0           # [osx]
  - 2022.12        # [win]
OSX_SDK_VER:       # [osx]
  - 13.3           # [osx]

# https://doc.qt.io/qt-6/windows.html
c_compiler:    # [win]
  - vs2022     # [win]
cxx_compiler:  # [win]
  - vs2022     # [win]

# XCode 15.0 came with SDK 14.0 and clang 15
# https://en.wikipedia.org/wiki/Xcode
c_compiler_version:    # [osx]
  - 17                 # [osx]
cxx_compiler_version:  # [osx]
  - 17                 # [osx]

# Have to leave this for now or else the overlinking checks fail when we revert back to the aggregate CBC and use the
# 12.1 sysroot.
CONDA_BUILD_SYSROOT:
  - /Library/Developer/CommandLineTools/SDKs/MacOSX13.3.sdk  # [osx and arm64]
